<a href="https://colab.research.google.com/github/dhhieu397/Techniques-in-Deep-Learning/blob/master/3_Word2vec.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Gán index cho các class bằng LabelEncoder:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
words = ['anh', 'em', 'gia đình', 'bạn bè', 'anh', 'em']
le.fit(words)
print('Class of words: ', le.classes_)
#Biến đổi sang dạng số
x = le.transform(words)
print('Convert to number: ', x)
#y = le.fit_transform(words)
#Biến đổi lại sang dạng class:
print('Invert into class: ', le.inverse_transform(x))

Class of words:  ['anh' 'bạn bè' 'em' 'gia đình']
Convert to number:  [0 2 3 1 0 2]
Invert into class:  ['anh' 'em' 'gia đình' 'bạn bè' 'anh' 'em']


In [ ]:
##Zip
x = [1, 2, 3]; y = ['a','b','c']
z = zip(x, y)
z = list(z)
print(z)
>>> [(1, 'a'), (2, 'b'), (3, 'c')]

In [ ]:
import numpy as np
x = le.classes_ #['anh', 'bạn bè', 'em', 'gia đình']
print(x1)
y = np.arange(len(le.classes_)) # [0 1 2 3]
print(x2)
z = zip(x, y)
z = list(z)
print(z)

['anh' 'bạn bè' 'em' 'gia đình']
4
[('anh', 0), ('bạn bè', 1), ('em', 2), ('gia đình', 3)]


In [ ]:
###OneHotEncoder
from sklearn.preprocessing import OneHotEncoder
import numpy as np
#x = np.arange(4)
#print(x.dtype) #int64
#print(x) #[0 1 2 3]
#len(le.classes_) #4
a = le.classes_
oh = OneHotEncoder()
classes_indices = list(zip(a, np.arange(len(le.classes_))))
print("Class indices: ", classes_indices)
oh.fit(classes_indices) #OneHotEncoder()
print('One-hot categories and indices:', oh.categories_) #[array(['anh', 'bạn bè', 'em', 'gia đình'], dtype=object), array([0, 1, 2, 3], dtype=object)]

#1. Biến đổi words sang dạng số
#print(words) # output: ['anh', 'em', 'gia đình', 'bạn bè', 'anh', 'em']
x = le.transform(words)
#print(x) # output: [0 2 3 1 0 2]
# zip(words, x)
#2. Biến đổi list words sang dạng one-hot
words_indices = list(zip(words, x))
print(words_indices) #output: [('anh', 0), ('em', 2), ('gia đình', 3), ('bạn bè', 1), ('anh', 0), ('em', 2)]

### 3. Transform words into one-hot matrices:
oneHot = oh.transform(words_indices).toarray()
print(oneHot)

### 4. Inverse transform to categories from one-hot matrices:
print(oh.inverse_transform(oneHot))



Class indices:  [('anh', 0), ('bạn bè', 1), ('em', 2), ('gia đình', 3)]
One-hot categories and indices: [array(['anh', 'bạn bè', 'em', 'gia đình'], dtype=object), array([0, 1, 2, 3], dtype=object)]
[('anh', 0), ('em', 2), ('gia đình', 3), ('bạn bè', 1), ('anh', 0), ('em', 2)]
[[1. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 1. 0.]]
[['anh' 0]
 ['em' 2]
 ['gia đình' 3]
 ['bạn bè' 1]
 ['anh' 0]
 ['em' 2]]
